# Constants
ROWS = 15
COLS = 15
TILE_SIZE = 48
SIDE_PANEL = 300
SCREEN_HEIGHT = ROWS * TILE_SIZE
SCREEN_WIDTH = COLS * TILE_SIZE
FPS = 60

# Player Constants
HEALTH = 40
MONEY = 650

# Enemy Constants
SPAWN_COOLDOWN = 400
TOTAL_LEVELS = 15
# Turret Constants
BUY_COST = 200
UPGRADE_COST = 100
ANIMATION_STEPS = 8
ANIMATION_DELAY = 15
LEVEL_REWARD = 50